# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = ["Visualizing Social Data"]

# Nav text
navTitleText = ["Soc 232"]

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Enter a copyright notice to display in the site footer.
copyright = "2021"

# Theme
theme = "cupper-hugo-theme"

# Get last modified date for content from Git?
enableGitInfo = false

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
pygmentsUseClasses = true

[outputs]
  home = [ "HTML", "RSS", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.nav]]
  name = "Class"
  url = "/class/"
  weight = 2.0

  [[menu.nav]]
  name = "Code"
  url = "/tags/code/"
  weight = 3.0

  [[menu.nav]]
  name = "Work"
  url = "/tags/work/"
  weight = 4.0

  [[menu.nav]]
  name = "Resources"
  url = "/resources/"
  weight = 5.0

## Slug specifications have to be at the end in TOML files
## Slug
[permalinks]
    post = "/:section/:slug/"
