# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = ["Visualizing Social Data"]

# Nav text
navTitleText = ["Soc 232"]

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Enter a copyright notice to display in the site footer.
copyright = "2021"

# Theme
theme = "cupper-hugo-theme"

# Get last modified date for content from Git?
enableGitInfo = false

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
pygmentsUseClasses = true


[params]
  my_name = "Kieran Healy"
  my_email = "kieran.healy@duke.edu"
  my_url = "https://kieranhealy.org"
  my_twitter = "kjhealy"
  my_github = "kjhealy"
  my_office = "268 Reuben-Cooke"
  my_contact_policy = "If you have questions or want to discuss things that we're doing in class, it's best to use the course Slack. I strongly encourage you not to be shy about raising queries or asking for help in the &#35;general channel. For other matters (such as absences, or to set up a meeting, etc), email me."
  crs_number = "SOCIOL 232"
  crs_semester = "Spring 2022"
  crs_days = "Mondays and Wednesdays"
  crs_time = "10:15am to 11:30am"
  crs_location = "Room 127, Reuben-Cooke"
  crs_dates = "Jan 5th - April 20th"
  crs_github = "kjhealy/vsd"
  crs_slack = "TBA"
  crs_copyrightYear = "2022"

[university]
name = "Duke University"
url = "https://www.duke.edu"

[school]
name = "Sociology Department"
url = "https://sociology.duke.edu/"

[outputs]
  home = [ "HTML", "RSS" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.nav]]
  name = "Class"
  url = "/class/"
  weight = 2.0

  [[menu.nav]]
  name = "Syllabus"
  url = "/syllabus/"
  weight = 3.0

  [[menu.nav]]
  name = "Resources"
  url = "/resources/"
  weight = 4.0

## Slug specifications have to be at the end in TOML files
## Slug
[permalinks]
    post = "/:section/:slug/"
